<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Diagnostics.EventLog" Version="9.0.20" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Clarion.Core\Clarion.Core.csproj" />
  </ItemGroup>

</Project>
